package metisimportmodel;
// default package
// Generated 06.09.2018 13:31:39 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dokfeldimport generated by hbm2java
 */
@Entity
@Table(name = "dokfeldimport", catalog = "metisimport")
public class Dokfeldimport implements java.io.Serializable {

	private Integer idDokFeld;
	private Dokumentimport dokumentimport;
	private int feldtypIdFeldTyp;
	private String feldinhalt;

	public Dokfeldimport() {
	}

	public Dokfeldimport(Dokumentimport dokumentimport, int feldtypIdFeldTyp) {
		this.dokumentimport = dokumentimport;
		this.feldtypIdFeldTyp = feldtypIdFeldTyp;
	}

	public Dokfeldimport(Dokumentimport dokumentimport, int feldtypIdFeldTyp, String feldinhalt) {
		this.dokumentimport = dokumentimport;
		this.feldtypIdFeldTyp = feldtypIdFeldTyp;
		this.feldinhalt = feldinhalt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDokFeld", unique = true, nullable = false)
	public Integer getIdDokFeld() {
		return this.idDokFeld;
	}

	public void setIdDokFeld(Integer idDokFeld) {
		this.idDokFeld = idDokFeld;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dokumentimport_idDokumentImport", nullable = false)
	public Dokumentimport getDokumentimport() {
		return this.dokumentimport;
	}

	public void setDokumentimport(Dokumentimport dokumentimport) {
		this.dokumentimport = dokumentimport;
	}

	@Column(name = "feldtyp_idFeldTyp", nullable = false)
	public int getFeldtypIdFeldTyp() {
		return this.feldtypIdFeldTyp;
	}

	public void setFeldtypIdFeldTyp(int feldtypIdFeldTyp) {
		this.feldtypIdFeldTyp = feldtypIdFeldTyp;
	}

	@Column(name = "Feldinhalt", length = 16777215)
	public String getFeldinhalt() {
		return this.feldinhalt;
	}

	public void setFeldinhalt(String feldinhalt) {
		this.feldinhalt = feldinhalt;
	}

}
