package metisimportmodel;
// default package
// Generated 06.09.2018 13:31:39 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dokjsonimport generated by hbm2java
 */
@Entity
@Table(name = "dokjsonimport", catalog = "metisimport")
public class Dokjsonimport implements java.io.Serializable {

	private Integer iddokjsonimport;
	private Dokumentimport dokumentimport;
	private int feldtypIdFeldTyp;
	private String feldinhalt;

	public Dokjsonimport() {
	}

	public Dokjsonimport(Dokumentimport dokumentimport, int feldtypIdFeldTyp) {
		this.dokumentimport = dokumentimport;
		this.feldtypIdFeldTyp = feldtypIdFeldTyp;
	}

	public Dokjsonimport(Dokumentimport dokumentimport, int feldtypIdFeldTyp, String feldinhalt) {
		this.dokumentimport = dokumentimport;
		this.feldtypIdFeldTyp = feldtypIdFeldTyp;
		this.feldinhalt = feldinhalt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddokjsonimport", unique = true, nullable = false)
	public Integer getIddokjsonimport() {
		return this.iddokjsonimport;
	}

	public void setIddokjsonimport(Integer iddokjsonimport) {
		this.iddokjsonimport = iddokjsonimport;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dokumentimport_idDokumentImport", nullable = false)
	public Dokumentimport getDokumentimport() {
		return this.dokumentimport;
	}

	public void setDokumentimport(Dokumentimport dokumentimport) {
		this.dokumentimport = dokumentimport;
	}

	@Column(name = "feldtyp_idFeldTyp", nullable = false)
	public int getFeldtypIdFeldTyp() {
		return this.feldtypIdFeldTyp;
	}

	public void setFeldtypIdFeldTyp(int feldtypIdFeldTyp) {
		this.feldtypIdFeldTyp = feldtypIdFeldTyp;
	}

	@Column(name = "feldinhalt", length = 16777215)
	public String getFeldinhalt() {
		return this.feldinhalt;
	}

	public void setFeldinhalt(String feldinhalt) {
		this.feldinhalt = feldinhalt;
	}

}
