package metisimportmodel;
// default package
// Generated 06.09.2018 13:31:39 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sonderdokumente generated by hbm2java
 */
@Entity
@Table(name = "sonderdokumente", catalog = "metisimport")
public class Sonderdokumente implements java.io.Serializable {

	private int idsonderdokumente;
	private String schluesselwort;
	private String gruppe;
	private Boolean metisImport;
	private Integer metisStatus;
	private Boolean dpsimport;

	public Sonderdokumente() {
	}

	public Sonderdokumente(int idsonderdokumente) {
		this.idsonderdokumente = idsonderdokumente;
	}

	public Sonderdokumente(int idsonderdokumente, String schluesselwort, String gruppe, Boolean metisImport,
			Integer metisStatus, Boolean dpsimport) {
		this.idsonderdokumente = idsonderdokumente;
		this.schluesselwort = schluesselwort;
		this.gruppe = gruppe;
		this.metisImport = metisImport;
		this.metisStatus = metisStatus;
		this.dpsimport = dpsimport;
	}

	@Id

	@Column(name = "idsonderdokumente", unique = true, nullable = false)
	public int getIdsonderdokumente() {
		return this.idsonderdokumente;
	}

	public void setIdsonderdokumente(int idsonderdokumente) {
		this.idsonderdokumente = idsonderdokumente;
	}

	@Column(name = "Schluesselwort")
	public String getSchluesselwort() {
		return this.schluesselwort;
	}

	public void setSchluesselwort(String schluesselwort) {
		this.schluesselwort = schluesselwort;
	}

	@Column(name = "Gruppe")
	public String getGruppe() {
		return this.gruppe;
	}

	public void setGruppe(String gruppe) {
		this.gruppe = gruppe;
	}

	@Column(name = "MetisImport")
	public Boolean getMetisImport() {
		return this.metisImport;
	}

	public void setMetisImport(Boolean metisImport) {
		this.metisImport = metisImport;
	}

	@Column(name = "MetisStatus")
	public Integer getMetisStatus() {
		return this.metisStatus;
	}

	public void setMetisStatus(Integer metisStatus) {
		this.metisStatus = metisStatus;
	}

	@Column(name = "DPSImport")
	public Boolean getDpsimport() {
		return this.dpsimport;
	}

	public void setDpsimport(Boolean dpsimport) {
		this.dpsimport = dpsimport;
	}

}
