package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Abfragen generated by hbm2java
 */
@Entity
@Table(name = "abfragen", catalog = "metis")
public class Abfragen implements java.io.Serializable {

	private int idAbfragen;
	private String kategorie;
	private String bezeichnung;
	private String abfragesql;
	private String bemerkung;
	private List<Rolle> rolles = new ArrayList<Rolle>();

	public Abfragen() {
	}

	public Abfragen(int idAbfragen) {
		this.idAbfragen = idAbfragen;
	}

	public Abfragen(int idAbfragen, String kategorie, String bezeichnung, String abfragesql, String bemerkung,
			List<Rolle> rolles) {
		this.idAbfragen = idAbfragen;
		this.kategorie = kategorie;
		this.bezeichnung = bezeichnung;
		this.abfragesql = abfragesql;
		this.bemerkung = bemerkung;
		this.rolles = rolles;
	}

	@Id

	@Column(name = "idAbfragen", unique = true, nullable = false)
	public int getIdAbfragen() {
		return this.idAbfragen;
	}

	public void setIdAbfragen(int idAbfragen) {
		this.idAbfragen = idAbfragen;
	}

	@Column(name = "Kategorie", length = 50)
	public String getKategorie() {
		return this.kategorie;
	}

	public void setKategorie(String kategorie) {
		this.kategorie = kategorie;
	}

	@Column(name = "Bezeichnung", length = 50)
	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	@Column(name = "Abfragesql")
	public String getAbfragesql() {
		return this.abfragesql;
	}

	public void setAbfragesql(String abfragesql) {
		this.abfragesql = abfragesql;
	}

	@Column(name = "Bemerkung")
	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "rolle_hat_abfragen", catalog = "metis", joinColumns = {
			@JoinColumn(name = "Abfragen_idabfragen", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Rolle_idrolle", nullable = false, updatable = false) })
	public List<Rolle> getRolles() {
		return this.rolles;
	}

	public void setRolles(List<Rolle> rolles) {
		this.rolles = rolles;
	}

	@Override
	public String toString() {
		return "Abfragen [idAbfragen=" + idAbfragen + ", kategorie=" + kategorie + ", bezeichnung=" + bezeichnung
				+ ", abfragesql=" + abfragesql + ", bemerkung=" + bemerkung + ", rolles=" + rolles + "]";
	}

	
	
	
}
