package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Abstract generated by hbm2java
 */
@Entity
@Table(name = "abstract", catalog = "metis")
public class Abstract implements java.io.Serializable {

	private Integer idabstract;
	private Dokument dokument;
	private Sprache sprache;
	private String abstract_;
	private String abstractAutor;

	public Abstract() {
	}

	public Abstract(Dokument dokument) {
		this.dokument = dokument;
	}

	public Abstract(Dokument dokument, Sprache sprache, String abstract_, String abstractAutor) {
		this.dokument = dokument;
		this.sprache = sprache;
		this.abstract_ = abstract_;
		this.abstractAutor = abstractAutor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idabstract", unique = true, nullable = false)
	public Integer getIdabstract() {
		return this.idabstract;
	}

	public void setIdabstract(Integer idabstract) {
		this.idabstract = idabstract;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dokument_iddokument", nullable = false)
	public Dokument getDokument() {
		return this.dokument;
	}

	public void setDokument(Dokument dokument) {
		this.dokument = dokument;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sprache_sprachcode")
	public Sprache getSprache() {
		return this.sprache;
	}

	public void setSprache(Sprache sprache) {
		this.sprache = sprache;
	}

	@Column(name = "Abstract", length = 16777215)
	public String getAbstract_() {
		return this.abstract_;
	}

	public void setAbstract_(String abstract_) {
		this.abstract_ = abstract_;
	}

	@Column(name = "AbstractAutor")
	public String getAbstractAutor() {
		return this.abstractAutor;
	}

	public void setAbstractAutor(String abstractAutor) {
		this.abstractAutor = abstractAutor;
	}

	@Override
	public String toString() {
		return "Abstract [idabstract=" + idabstract + ", dokument=" + dokument + ", sprache=" + sprache + ", abstract_="
				+ abstract_ + ", abstractAutor=" + abstractAutor + "]";
	}

}
