package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Allesprachen generated by hbm2java
 */
@Entity
@Table(name = "allesprachen", catalog = "metis")
public class Allesprachen implements java.io.Serializable {

	private String iso6392;
	private String iso6391;
	private String language;
	private String langue;
	private String sprache;
	private Sprache sprache1;

	public Allesprachen() {
	}

	public Allesprachen(String iso6392) {
		this.iso6392 = iso6392;
	}

	public Allesprachen(String iso6392, String iso6391, String language, String langue, String sprache,
			Sprache sprache1) {
		this.iso6392 = iso6392;
		this.iso6391 = iso6391;
		this.language = language;
		this.langue = langue;
		this.sprache = sprache;
		this.sprache1 = sprache1;
	}

	@Id

	@Column(name = "ISO639_2", unique = true, nullable = false, length = 3)
	public String getIso6392() {
		return this.iso6392;
	}

	public void setIso6392(String iso6392) {
		this.iso6392 = iso6392;
	}

	@Column(name = "ISO639_1", length = 2)
	public String getIso6391() {
		return this.iso6391;
	}

	public void setIso6391(String iso6391) {
		this.iso6391 = iso6391;
	}

	@Column(name = "language", length = 50)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "langue", length = 50)
	public String getLangue() {
		return this.langue;
	}

	public void setLangue(String langue) {
		this.langue = langue;
	}

	@Column(name = "Sprache", length = 50)
	public String getSprache() {
		return this.sprache;
	}

	public void setSprache(String sprache) {
		this.sprache = sprache;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "allesprachen")
	public Sprache getSprache1() {
		return this.sprache1;
	}

	public void setSprache1(Sprache sprache1) {
		this.sprache1 = sprache1;
	}

}
