package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ausfallzeit generated by hbm2java
 */
@Entity
@Table(name = "ausfallzeit", catalog = "metis")
public class Ausfallzeit implements java.io.Serializable {

	private AusfallzeitId id;
	private Bearbeiter bearbeiter;
	private Date von;
	private Date bis;
	private String bemerkung;

	public Ausfallzeit() {
	}

	public Ausfallzeit(AusfallzeitId id, Bearbeiter bearbeiter) {
		this.id = id;
		this.bearbeiter = bearbeiter;
	}

	public Ausfallzeit(AusfallzeitId id, Bearbeiter bearbeiter, Date von, Date bis, String bemerkung) {
		this.id = id;
		this.bearbeiter = bearbeiter;
		this.von = von;
		this.bis = bis;
		this.bemerkung = bemerkung;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAusfallzeit", column = @Column(name = "idausfallzeit", nullable = false)),
			@AttributeOverride(name = "bearbeiterIdBearbeiter", column = @Column(name = "Bearbeiter_idbearbeiter", nullable = false)) })
	public AusfallzeitId getId() {
		return this.id;
	}

	public void setId(AusfallzeitId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Bearbeiter_idbearbeiter", nullable = false, insertable = false, updatable = false)
	public Bearbeiter getBearbeiter() {
		return this.bearbeiter;
	}

	public void setBearbeiter(Bearbeiter bearbeiter) {
		this.bearbeiter = bearbeiter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "von", length = 10)
	public Date getVon() {
		return this.von;
	}

	public void setVon(Date von) {
		this.von = von;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "bis", length = 10)
	public Date getBis() {
		return this.bis;
	}

	public void setBis(Date bis) {
		this.bis = bis;
	}

	@Column(name = "Bemerkung")
	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	@Override
	public String toString() {
		return "Ausfallzeit [id=" + id + ", bearbeiter=" + bearbeiter + ", von=" + von + ", bis=" + bis + ", bemerkung="
				+ bemerkung + "]";
	}

	
	
	
}
