package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auswertungstaetigkeit generated by hbm2java
 */
@Entity
@Table(name = "auswertungstaetigkeit", catalog = "metis")
public class Auswertungstaetigkeit implements java.io.Serializable {

	private int idAuswertungstaetigkeit;
	private String taetigkeit;
	private String verguetung;
	private String beschreibung;
	private List<Dokument> dokuments = new ArrayList<Dokument>();
	private List<Bearbeiter> bearbeiters = new ArrayList<Bearbeiter>();

	public Auswertungstaetigkeit() {
	}

	public Auswertungstaetigkeit(String taetigkeit, String verguetung, String beschreibung, List<Dokument> dokuments,
			List<Bearbeiter> bearbeiters) {
		this.taetigkeit = taetigkeit;
		this.verguetung = verguetung;
		this.beschreibung = beschreibung;
		this.dokuments = dokuments;
		this.bearbeiters = bearbeiters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idauswertungstaetigkeit", unique = true, nullable = false)
	public int getIdAuswertungstaetigkeit() {
		return this.idAuswertungstaetigkeit;
	}

	public void setIdAuswertungstaetigkeit(int idAuswertungstaetigkeit) {
		this.idAuswertungstaetigkeit = idAuswertungstaetigkeit;
	}

	@Column(name = "Taetigkeit", length = 45)
	public String getTaetigkeit() {
		return this.taetigkeit;
	}

	public void setTaetigkeit(String taetigkeit) {
		this.taetigkeit = taetigkeit;
	}

	@Column(name = "Verguetung", length = 45)
	public String getVerguetung() {
		return this.verguetung;
	}

	public void setVerguetung(String verguetung) {
		this.verguetung = verguetung;
	}

	@Column(name = "Beschreibung")
	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "auswertungstaetigkeit")
	public List<Dokument> getDokuments() {
		return this.dokuments;
	}

	public void setDokuments(List<Dokument> dokuments) {
		this.dokuments = dokuments;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "bearbeiter_darf_auswertungstaetigkeit", catalog = "metis", joinColumns = {
			@JoinColumn(name = "auswertungstaetigkeit_idaauswertungstaetigkeit", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "bearbeiter_idbearbeiter", nullable = false, updatable = false) })
	public List<Bearbeiter> getBearbeiters() {
		return this.bearbeiters;
	}

	public void setBearbeiters(List<Bearbeiter> bearbeiters) {
		this.bearbeiters = bearbeiters;
	}

	@Override
	public String toString() {
		return "Auswertungstaetigkeit [idAuswertungstaetigkeit=" + idAuswertungstaetigkeit + ", taetigkeit="
				+ taetigkeit + ", verguetung=" + verguetung + ", beschreibung=" + beschreibung + ", dokuments="
				+ dokuments + ", bearbeiters=" + bearbeiters + "]";
	}

	
	
	
}
