package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.transaction.annotation.Transactional;

/**
 * Autor generated by hbm2java
 */
@Entity
@Table(name = "autor", catalog = "metis")
public class Autor implements java.io.Serializable {

	private int idAutor;
	private String name;
	private String vorname;
	private String vornamekrz;
	private String orcid;
	private String viaf;
	private List<DokumentHatAutor> dokumentHatAutors = new ArrayList<DokumentHatAutor>();

	public Autor() {
	}

	public Autor(String name, String vorname, String vornamekrz, String orcid, String viaf,
			List<DokumentHatAutor> dokumentHatAutors) {
		this.name = name;
		this.vorname = vorname;
		this.vornamekrz = vornamekrz;
		this.orcid = orcid;
		this.viaf = viaf;
		this.dokumentHatAutors = dokumentHatAutors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idautor", unique = true, nullable = false)
	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	@Column(name = "Name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Vorname", length = 45)
	public String getVorname() {
		return this.vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}

	@Column(name = "Vornamekrz", length = 45)
	public String getVornamekrz() {
		return this.vornamekrz;
	}

	public void setVornamekrz(String vornamekrz) {
		this.vornamekrz = vornamekrz;
	}

	@Column(name = "ORCID", length = 45)
	public String getOrcid() {
		return this.orcid;
	}

	public void setOrcid(String orcid) {
		this.orcid = orcid;
	}

	@Column(name = "VIAF")
	public String getViaf() {
		return this.viaf;
	}

	public void setViaf(String viaf) {
		this.viaf = viaf;
	}
	@Transactional
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "autor")
	public List<DokumentHatAutor> getDokumentHatAutors() {
		return this.dokumentHatAutors;
	}

	public void setDokumentHatAutors(List<DokumentHatAutor> dokumentHatAutors) {
		this.dokumentHatAutors = dokumentHatAutors;
	}

	@Override
	public String toString() {
		return "Autor [idAutor=" + idAutor + ", name=" + name + ", vorname=" + vorname + ", vornamekrz=" + vornamekrz
				+ ", orcid=" + orcid + ", viaf=" + viaf + ", dokumentHatAutors=" + dokumentHatAutors + "]";
	}

}
