package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BearbeiterKannSprache generated by hbm2java
 */
@Entity
@Table(name = "bearbeiter_kann_sprache", catalog = "metis")
public class BearbeiterKannSprache implements java.io.Serializable {

	private BearbeiterKannSpracheId id;
	private Bearbeiter bearbeiter;
	private Sprache sprache;
	private String bemerkung;

	public BearbeiterKannSprache() {
	}

	public BearbeiterKannSprache(BearbeiterKannSpracheId id, Bearbeiter bearbeiter, Sprache sprache) {
		this.id = id;
		this.bearbeiter = bearbeiter;
		this.sprache = sprache;
	}

	public BearbeiterKannSprache(BearbeiterKannSpracheId id, Bearbeiter bearbeiter, Sprache sprache, String bemerkung) {
		this.id = id;
		this.bearbeiter = bearbeiter;
		this.sprache = sprache;
		this.bemerkung = bemerkung;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "bearbeiterIdBearbeiter", column = @Column(name = "Bearbeiter_idbearbeiter", nullable = false)),
			@AttributeOverride(name = "spracheSprachcode", column = @Column(name = "Sprache_sprachcode", nullable = false, length = 2)) })
	public BearbeiterKannSpracheId getId() {
		return this.id;
	}

	public void setId(BearbeiterKannSpracheId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Bearbeiter_idbearbeiter", nullable = false, insertable = false, updatable = false)
	public Bearbeiter getBearbeiter() {
		return this.bearbeiter;
	}

	public void setBearbeiter(Bearbeiter bearbeiter) {
		this.bearbeiter = bearbeiter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Sprache_sprachcode", nullable = false, insertable = false, updatable = false)
	public Sprache getSprache() {
		return this.sprache;
	}

	public void setSprache(Sprache sprache) {
		this.sprache = sprache;
	}

	@Column(name = "Bemerkung")
	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	@Override
	public String toString() {
		return "BearbeiterKannSprache [id=" + id + ", bearbeiter=" + bearbeiter + ", sprache=" + sprache
				+ ", bemerkung=" + bemerkung + "]";
	}

}
