package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BearbeiterKannSpracheId generated by hbm2java
 */
@Embeddable
public class BearbeiterKannSpracheId implements java.io.Serializable {

	private int bearbeiterIdBearbeiter;
	private String spracheSprachcode;

	public BearbeiterKannSpracheId() {
	}

	public BearbeiterKannSpracheId(int bearbeiterIdBearbeiter, String spracheSprachcode) {
		this.bearbeiterIdBearbeiter = bearbeiterIdBearbeiter;
		this.spracheSprachcode = spracheSprachcode;
	}

	@Column(name = "Bearbeiter_idbearbeiter", nullable = false)
	public int getBearbeiterIdBearbeiter() {
		return this.bearbeiterIdBearbeiter;
	}

	public void setBearbeiterIdBearbeiter(int bearbeiterIdBearbeiter) {
		this.bearbeiterIdBearbeiter = bearbeiterIdBearbeiter;
	}

	@Column(name = "Sprache_sprachcode", nullable = false, length = 2)
	public String getSpracheSprachcode() {
		return this.spracheSprachcode;
	}

	public void setSpracheSprachcode(String spracheSprachcode) {
		this.spracheSprachcode = spracheSprachcode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BearbeiterKannSpracheId))
			return false;
		BearbeiterKannSpracheId castOther = (BearbeiterKannSpracheId) other;

		return (this.getBearbeiterIdBearbeiter() == castOther.getBearbeiterIdBearbeiter())
				&& ((this.getSpracheSprachcode() == castOther.getSpracheSprachcode())
						|| (this.getSpracheSprachcode() != null && castOther.getSpracheSprachcode() != null
								&& this.getSpracheSprachcode().equals(castOther.getSpracheSprachcode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBearbeiterIdBearbeiter();
		result = 37 * result + (getSpracheSprachcode() == null ? 0 : this.getSpracheSprachcode().hashCode());
		return result;
	}

}
