package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Berechtigung generated by hbm2java
 */
@Entity
@Table(name = "berechtigung", catalog = "metis")
public class Berechtigung implements java.io.Serializable {

	private int idBerechtigung;
	private String berechtigung;
	private String beschreibung;
	private List<Rolle> rolles = new ArrayList<Rolle>();
	private List<Module> modules = new ArrayList<Module>();

	public Berechtigung() {
	}

	public Berechtigung(String berechtigung, String beschreibung, List<Rolle> rolles, List<Module> modules) {
		this.berechtigung = berechtigung;
		this.beschreibung = beschreibung;
		this.rolles = rolles;
		this.modules = modules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idberechtigung", unique = true, nullable = false)
	public int getIdBerechtigung() {
		return this.idBerechtigung;
	}

	public void setIdBerechtigung(int idBerechtigung) {
		this.idBerechtigung = idBerechtigung;
	}

	@Column(name = "Berechtigung", length = 45)
	public String getBerechtigung() {
		return this.berechtigung;
	}

	public void setBerechtigung(String berechtigung) {
		this.berechtigung = berechtigung;
	}

	@Column(name = "Beschreibung")
	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "rolle_hat_berechtigung", catalog = "metis", joinColumns = {
			@JoinColumn(name = "Berechtigung_idberechtigung", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Rolle_idrolle", nullable = false, updatable = false) })
	public List<Rolle> getRolles() {
		return this.rolles;
	}

	public void setRolles(List<Rolle> rolles) {
		this.rolles = rolles;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "berechtigung_nutzt_module", catalog = "metis", joinColumns = {
			@JoinColumn(name = "Berechtigung_idberechtigung", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Module_idmodule", nullable = false, updatable = false) })
	public List<Module> getModules() {
		return this.modules;
	}

	public void setModules(List<Module> modules) {
		this.modules = modules;
	}

	@Override
	public String toString() {
		return "Berechtigung [idBerechtigung=" + idBerechtigung + ", berechtigung=" + berechtigung + ", beschreibung="
				+ beschreibung + ", rolles=" + rolles + ", modules=" + modules + "]";
	}

	
	
	
}
