package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dateilink generated by hbm2java
 */
@Entity
@Table(name = "dateilink", catalog = "metis")
public class Dateilink implements java.io.Serializable {

	private int idDatei;
	private Dokument dokument;
	private String dateityp;
	private String relativerPfad;

	public Dateilink() {
	}

	public Dateilink(Dokument dokument) {
		this.dokument = dokument;
	}

	public Dateilink(Dokument dokument, String dateityp, String relativerPfad) {
		this.dokument = dokument;
		this.dateityp = dateityp;
		this.relativerPfad = relativerPfad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddatei", unique = true, nullable = false)
	public int getIdDatei() {
		return this.idDatei;
	}

	public void setIdDatei(int idDatei) {
		this.idDatei = idDatei;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Dokument_iddokument", nullable = false)
	public Dokument getDokument() {
		return this.dokument;
	}

	public void setDokument(Dokument dokument) {
		this.dokument = dokument;
	}

	@Column(name = "Dateityp", length = 10)
	public String getDateityp() {
		return this.dateityp;
	}

	public void setDateityp(String dateityp) {
		this.dateityp = dateityp;
	}

	@Column(name = "relativerpfad")
	public String getRelativerPfad() {
		return this.relativerPfad;
	}

	public void setRelativerPfad(String relativerPfad) {
		this.relativerPfad = relativerPfad;
	}

	@Override
	public String toString() {
		return "Dateilink [idDatei=" + idDatei + ", dokument=" + dokument + ", dateityp=" + dateityp
				+ ", relativerPfad=" + relativerPfad + "]";
	}

	
	
	
}
