package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dokfeld generated by hbm2java
 */
@Entity
@Table(name = "dokfeld", catalog = "metis")
public class Dokfeld implements java.io.Serializable {

	private int idDokFeld;
	private Dokument dokument;
	private Feldtyp feldtyp;
	private String feldinhalt;

	public Dokfeld() {
	}

	public Dokfeld(int idDokFeld, Dokument dokument, Feldtyp feldtyp) {
		this.idDokFeld = idDokFeld;
		this.dokument = dokument;
		this.feldtyp = feldtyp;
	}

	public Dokfeld(int idDokFeld, Dokument dokument, Feldtyp feldtyp, String feldinhalt) {
		this.idDokFeld = idDokFeld;
		this.dokument = dokument;
		this.feldtyp = feldtyp;
		this.feldinhalt = feldinhalt;
	}

	@Id

	@Column(name = "iddokfeld", unique = true, nullable = false)
	public int getIdDokFeld() {
		return this.idDokFeld;
	}

	public void setIdDokFeld(int idDokFeld) {
		this.idDokFeld = idDokFeld;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Dokument_iddokument", nullable = false)
	public Dokument getDokument() {
		return this.dokument;
	}

	public void setDokument(Dokument dokument) {
		this.dokument = dokument;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feldtyp_idfeldtyp", nullable = false)
	public Feldtyp getFeldtyp() {
		return this.feldtyp;
	}

	public void setFeldtyp(Feldtyp feldtyp) {
		this.feldtyp = feldtyp;
	}

	@Column(name = "Feldinhalt", length = 16777215)
	public String getFeldinhalt() {
		return this.feldinhalt;
	}

	public void setFeldinhalt(String feldinhalt) {
		this.feldinhalt = feldinhalt;
	}

	@Override
	public String toString() {
		return "Dokfeld [idDokFeld=" + idDokFeld + ", dokument=" + dokument + ", feldtyp=" + feldtyp + ", feldinhalt="
				+ feldinhalt + "]";
	}

	
	
	
}
