package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Dokumentart generated by hbm2java
 */
@Entity
@Table(name = "dokumentart", catalog = "metis")
public class Dokumentart implements java.io.Serializable {

	private String idDokumentart;
	private String bezeichnung;
	private String ebezeichnung;
	private String bemerkung;
	private List<Dokument> dokuments = new ArrayList<Dokument>();
	private List<Periodika> periodikas = new ArrayList<Periodika>();
	private List<Quelle> quelles = new ArrayList<Quelle>();

	public Dokumentart() {
	}

	public Dokumentart(String idDokumentart) {
		this.idDokumentart = idDokumentart;
	}

	public Dokumentart(String idDokumentart, String bezeichnung, String ebezeichnung, String bemerkung,
			List<Dokument> dokuments, List<Periodika> periodikas, List<Quelle> quelles) {
		this.idDokumentart = idDokumentart;
		this.bezeichnung = bezeichnung;
		this.ebezeichnung = ebezeichnung;
		this.bemerkung = bemerkung;
		this.dokuments = dokuments;
		this.periodikas = periodikas;
		this.quelles = quelles;
	}

	@Id

	@Column(name = "iddokumentart", unique = true, nullable = false, length = 2)
	public String getIdDokumentart() {
		return this.idDokumentart;
	}

	public void setIdDokumentart(String idDokumentart) {
		this.idDokumentart = idDokumentart;
	}

	@Column(name = "Bezeichnung", length = 50)
	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	@Column(name = "ebezeichnung", length = 50)
	public String getEbezeichnung() {
		return this.ebezeichnung;
	}

	public void setEbezeichnung(String ebezeichnung) {
		this.ebezeichnung = ebezeichnung;
	}

	@Column(name = "Bemerkung")
	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "dokument_hat_dokumentart", catalog = "metis", joinColumns = {
			@JoinColumn(name = "Dokumentart_iddokumentart", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Dokument_iddokument", nullable = false, updatable = false) })
	public List<Dokument> getDokuments() {
		return this.dokuments;
	}

	public void setDokuments(List<Dokument> dokuments) {
		this.dokuments = dokuments;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "periodika_hat_dokumentart", catalog = "metis", joinColumns = {
			@JoinColumn(name = "Dokumentart_iddokumentart", nullable = false, updatable = false)  })
	public List<Periodika> getPeriodikas() {
		return this.periodikas;
	}

	public void setPeriodikas(List<Periodika> periodikas) {
		this.periodikas = periodikas;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "quelle_hat_dokumentart", catalog = "metis", joinColumns = {
			@JoinColumn(name = "Dokumentart_iddokumentart", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Quelle_idquelle", nullable = false, updatable = false) })
	public List<Quelle> getQuelles() {
		return this.quelles;
	}

	public void setQuelles(List<Quelle> quelles) {
		this.quelles = quelles;
	}

	@Override
	public String toString() {
		return "Dokumentart [idDokumentart=" + idDokumentart + ", bezeichnung=" + bezeichnung + ", ebezeichnung="
				+ ebezeichnung + ", bemerkung=" + bemerkung + ", dokuments=" + dokuments + ", periodikas=" + periodikas
				+ ", quelles=" + quelles + "]";
	}
	
	
	

}
