package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DokumentHatDeskriptor generated by hbm2java
 */
@Entity
@Table(name = "dokument_hat_deskriptor", catalog = "metis")
public class DokumentHatDeskriptor implements java.io.Serializable {

	private DokumentHatDeskriptorId id;
	private Dokument dokument;
	private ThesaurusTemaTerm thesaurusTemaTerm;
	private Boolean autindex;
	private Boolean hauptdeskriptor;

	public DokumentHatDeskriptor() {
	}

	public DokumentHatDeskriptor(DokumentHatDeskriptorId id, Dokument dokument, ThesaurusTemaTerm thesaurusTemaTerm) {
		this.id = id;
		this.dokument = dokument;
		this.thesaurusTemaTerm = thesaurusTemaTerm;
	}

	public DokumentHatDeskriptor(DokumentHatDeskriptorId id, Dokument dokument, ThesaurusTemaTerm thesaurusTemaTerm,
			Boolean autindex, Boolean hauptdeskriptor) {
		this.id = id;
		this.dokument = dokument;
		this.thesaurusTemaTerm = thesaurusTemaTerm;
		this.autindex = autindex;
		this.hauptdeskriptor = hauptdeskriptor;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dokumentIdDokument", column = @Column(name = "dokument_iddokument", nullable = false)),
			@AttributeOverride(name = "temaTermTermnr", column = @Column(name = "tema_term_termnr", nullable = false)) })
	public DokumentHatDeskriptorId getId() {
		return this.id;
	}

	public void setId(DokumentHatDeskriptorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dokument_iddokument", nullable = false, insertable = false, updatable = false)
	public Dokument getDokument() {
		return this.dokument;
	}

	public void setDokument(Dokument dokument) {
		this.dokument = dokument;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tema_term_termnr", nullable = false, insertable = false, updatable = false)
	public ThesaurusTemaTerm getThesaurusTemaTerm() {
		return this.thesaurusTemaTerm;
	}

	public void setThesaurusTemaTerm(ThesaurusTemaTerm thesaurusTemaTerm) {
		this.thesaurusTemaTerm = thesaurusTemaTerm;
	}

	@Column(name = "Autindex")
	public Boolean getAutindex() {
		return this.autindex;
	}

	public void setAutindex(Boolean autindex) {
		this.autindex = autindex;
	}

	@Column(name = "Hauptdeskriptor")
	public Boolean getHauptdeskriptor() {
		return this.hauptdeskriptor;
	}

	public void setHauptdeskriptor(Boolean hauptdeskriptor) {
		this.hauptdeskriptor = hauptdeskriptor;
	}

	@Override
	public String toString() {
		return "DokumentHatDeskriptor [id=" + id + ", dokument=" + dokument + ", thesaurusTemaTerm=" + thesaurusTemaTerm
				+ ", autindex=" + autindex + ", hauptdeskriptor=" + hauptdeskriptor + "]";
	}

}
