package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DokumentHatAutorId generated by hbm2java
 */
@Embeddable
public class DokumentHatAutorId implements java.io.Serializable {

	private int autorIdAutor;
	private int dokumentIdDokument;

	public DokumentHatAutorId() {
	}

	public DokumentHatAutorId(int autorIdAutor, int dokumentIdDokument) {
		this.autorIdAutor = autorIdAutor;
		this.dokumentIdDokument = dokumentIdDokument;
	}

	@Column(name = "Autor_idautor", nullable = false)
	public int getAutorIdAutor() {
		return this.autorIdAutor;
	}

	public void setAutorIdAutor(int autorIdAutor) {
		this.autorIdAutor = autorIdAutor;
	}

	@Column(name = "Dokument_iddokument", nullable = false)
	public int getDokumentIdDokument() {
		return this.dokumentIdDokument;
	}

	public void setDokumentIdDokument(int dokumentIdDokument) {
		this.dokumentIdDokument = dokumentIdDokument;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DokumentHatAutorId))
			return false;
		DokumentHatAutorId castOther = (DokumentHatAutorId) other;

		return (this.getAutorIdAutor() == castOther.getAutorIdAutor())
				&& (this.getDokumentIdDokument() == castOther.getDokumentIdDokument());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAutorIdAutor();
		result = 37 * result + this.getDokumentIdDokument();
		return result;
	}

}
