package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DokumentHatFreierbegriffId generated by hbm2java
 */
@Embeddable
public class DokumentHatFreierbegriffId implements java.io.Serializable {

	private int dokumentIdDokument;
	private int freieBegriffeIdfreieBegriffe;

	public DokumentHatFreierbegriffId() {
	}

	public DokumentHatFreierbegriffId(int dokumentIdDokument, int freieBegriffeIdfreieBegriffe) {
		this.dokumentIdDokument = dokumentIdDokument;
		this.freieBegriffeIdfreieBegriffe = freieBegriffeIdfreieBegriffe;
	}

	@Column(name = "Dokument_iddokument", nullable = false)
	public int getDokumentIdDokument() {
		return this.dokumentIdDokument;
	}

	public void setDokumentIdDokument(int dokumentIdDokument) {
		this.dokumentIdDokument = dokumentIdDokument;
	}

	@Column(name = "freiebegriffe_idfreiebegriffe", nullable = false)
	public int getFreieBegriffeIdfreieBegriffe() {
		return this.freieBegriffeIdfreieBegriffe;
	}

	public void setFreieBegriffeIdfreieBegriffe(int freieBegriffeIdfreieBegriffe) {
		this.freieBegriffeIdfreieBegriffe = freieBegriffeIdfreieBegriffe;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DokumentHatFreierbegriffId))
			return false;
		DokumentHatFreierbegriffId castOther = (DokumentHatFreierbegriffId) other;

		return (this.getDokumentIdDokument() == castOther.getDokumentIdDokument())
				&& (this.getFreieBegriffeIdfreieBegriffe() == castOther.getFreieBegriffeIdfreieBegriffe());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDokumentIdDokument();
		result = 37 * result + this.getFreieBegriffeIdfreieBegriffe();
		return result;
	}

}
