package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DokumentHatFreierbegriff generated by hbm2java
 */
@Entity
@Table(name = "dokument_hat_freierbegriff", catalog = "metis")
public class DokumentHatFreierbegriff implements java.io.Serializable {

	private DokumentHatFreierbegriffId id;
	private Dokument dokument;
	private Freierbegriff freierbegriff;
	private Boolean autindex;

	public DokumentHatFreierbegriff() {
	}

	public DokumentHatFreierbegriff(DokumentHatFreierbegriffId id, Dokument dokument, Freierbegriff freierbegriff) {
		this.id = id;
		this.dokument = dokument;
		this.freierbegriff = freierbegriff;
	}

	public DokumentHatFreierbegriff(DokumentHatFreierbegriffId id, Dokument dokument, Freierbegriff freierbegriff,
			Boolean autindex) {
		this.id = id;
		this.dokument = dokument;
		this.freierbegriff = freierbegriff;
		this.autindex = autindex;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dokumentIdDokument", column = @Column(name = "Dokument_iddokument", nullable = false)),
			@AttributeOverride(name = "freieBegriffeIdfreieBegriffe", column = @Column(name = "freiebegriffe_idfreiebegriffe", nullable = false)) })
	public DokumentHatFreierbegriffId getId() {
		return this.id;
	}

	public void setId(DokumentHatFreierbegriffId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Dokument_iddokument", nullable = false, insertable = false, updatable = false)
	public Dokument getDokument() {
		return this.dokument;
	}

	public void setDokument(Dokument dokument) {
		this.dokument = dokument;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "freiebegriffe_idfreiebegriffe", nullable = false, insertable = false, updatable = false)
	public Freierbegriff getFreierbegriff() {
		return this.freierbegriff;
	}

	public void setFreierbegriff(Freierbegriff freierbegriff) {
		this.freierbegriff = freierbegriff;
	}

	@Column(name = "Autindex")
	public Boolean getAutindex() {
		return this.autindex;
	}

	public void setAutindex(Boolean autindex) {
		this.autindex = autindex;
	}

	@Override
	public String toString() {
		return "DokumentHatFreierbegriff [id=" + id + ", dokument=" + dokument + ", freierbegriff=" + freierbegriff
				+ ", autindex=" + autindex + "]";
	}

}
