package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Dokumentform generated by hbm2java
 */
@Entity
@Table(name = "dokumentform", catalog = "metis")
public class Dokumentform implements java.io.Serializable {

	private String idDokumentform;
	private String bezeichnung;
	private String ebezeichnung;
	private String bemerkung;
	private List<Dokument> dokuments = new ArrayList<Dokument>();
	private List<Periodika> periodikas = new ArrayList<Periodika>();
	private List<Quelle> quelles = new ArrayList<Quelle>();

	public Dokumentform() {
	}

	public Dokumentform(String idDokumentform) {
		this.idDokumentform = idDokumentform;
	}

	public Dokumentform(String idDokumentform, String bezeichnung, String ebezeichnung, String bemerkung,
			List<Dokument> dokuments, List<Periodika> periodikas, List<Quelle> quelles) {
		this.idDokumentform = idDokumentform;
		this.bezeichnung = bezeichnung;
		this.ebezeichnung = ebezeichnung;
		this.bemerkung = bemerkung;
		this.dokuments = dokuments;
		this.periodikas = periodikas;
		this.quelles = quelles;
	}

	@Id

	@Column(name = "iddokumentform", unique = true, nullable = false, length = 2)
	public String getIdDokumentform() {
		return this.idDokumentform;
	}

	public void setIdDokumentform(String idDokumentform) {
		this.idDokumentform = idDokumentform;
	}

	@Column(name = "Bezeichnung", length = 50)
	public String getBezeichnung() {
		return this.bezeichnung;
	}

	public void setBezeichnung(String bezeichnung) {
		this.bezeichnung = bezeichnung;
	}

	@Column(name = "ebezeichnung", length = 50)
	public String getEbezeichnung() {
		return this.ebezeichnung;
	}

	public void setEbezeichnung(String ebezeichnung) {
		this.ebezeichnung = ebezeichnung;
	}

	@Column(name = "Bemerkung")
	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "dokument_hat_dokumentform", catalog = "metis", joinColumns = {
			@JoinColumn(name = "Dokumentform_iddokumentform", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Dokument_iddokument", nullable = false, updatable = false) })
	public List<Dokument> getDokuments() {
		return this.dokuments;
	}

	public void setDokuments(List<Dokument> dokuments) {
		this.dokuments = dokuments;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "Dokumentform_iddokumentform", nullable = false, updatable = false) 
			
	public List<Periodika> getPeriodikas() {
		return this.periodikas;
	}

	public void setPeriodikas(List<Periodika> periodikas) {
		this.periodikas = periodikas;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "Dokumentform_iddokumentform", nullable = false, updatable = false) 		
	public List<Quelle> getQuelles() {
		return this.quelles;
	}

	public void setQuelles(List<Quelle> quelles) {
		this.quelles = quelles;
	}

	@Override
	public String toString() {
		return "Dokumentform [idDokumentform=" + idDokumentform + ", bezeichnung=" + bezeichnung + ", ebezeichnung="
				+ ebezeichnung + ", bemerkung=" + bemerkung + ", dokuments=" + dokuments + ", periodikas=" + periodikas
				+ ", quelles=" + quelles + "]";
	}

}
