package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DokumentHatDeskriptorId generated by hbm2java
 */
@Embeddable
public class DokumentHatDeskriptorId implements java.io.Serializable {

	private int dokumentIdDokument;
	private int temaTermTermnr;

	public DokumentHatDeskriptorId() {
	}

	public DokumentHatDeskriptorId(int dokumentIdDokument, int temaTermTermnr) {
		this.dokumentIdDokument = dokumentIdDokument;
		this.temaTermTermnr = temaTermTermnr;
	}

	@Column(name = "dokument_iddokument", nullable = false)
	public int getDokumentIdDokument() {
		return this.dokumentIdDokument;
	}

	public void setDokumentIdDokument(int dokumentIdDokument) {
		this.dokumentIdDokument = dokumentIdDokument;
	}

	@Column(name = "tema_term_termnr", nullable = false)
	public int getTemaTermTermnr() {
		return this.temaTermTermnr;
	}

	public void setTemaTermTermnr(int temaTermTermnr) {
		this.temaTermTermnr = temaTermTermnr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DokumentHatDeskriptorId))
			return false;
		DokumentHatDeskriptorId castOther = (DokumentHatDeskriptorId) other;

		return (this.getDokumentIdDokument() == castOther.getDokumentIdDokument())
				&& (this.getTemaTermTermnr() == castOther.getTemaTermTermnr());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getDokumentIdDokument();
		result = 37 * result + this.getTemaTermTermnr();
		return result;
	}

}
