package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.transaction.annotation.Transactional;

/**
 * DokumentHatAutor generated by hbm2java
 */
@Entity
@Table(name = "dokument_hat_autor", catalog = "metis")
public class DokumentHatAutor implements java.io.Serializable {

	private DokumentHatAutorId id;
	private Autor autor;
	private Dokument dokument;
	private String bemerkung;

	public DokumentHatAutor() {
	}

	public DokumentHatAutor(DokumentHatAutorId id, Autor autor, Dokument dokument) {
		this.id = id;
		this.autor = autor;
		this.dokument = dokument;
	}

	public DokumentHatAutor(DokumentHatAutorId id, Autor autor, Dokument dokument, String bemerkung) {
		this.id = id;
		this.autor = autor;
		this.dokument = dokument;
		this.bemerkung = bemerkung;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "autorIdAutor", column = @Column(name = "Autor_idautor", nullable = false)),
			@AttributeOverride(name = "dokumentIdDokument", column = @Column(name = "Dokument_iddokument", nullable = false)) })
	public DokumentHatAutorId getId() {
		return this.id;
	}

	public void setId(DokumentHatAutorId id) {
		this.id = id;
	}
	@Transactional
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Autor_idautor", nullable = false, insertable = false, updatable = false)
	public Autor getAutor() {
		return this.autor;
	}

	public void setAutor(Autor autor) {
		this.autor = autor;
	}
	@Transactional
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Dokument_iddokument", nullable = false, insertable = false, updatable = false)
	public Dokument getDokument() {
		return this.dokument;
	}

	public void setDokument(Dokument dokument) {
		this.dokument = dokument;
	}

	@Column(name = "Bemerkung")
	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	@Override
	public String toString() {
		return "DokumentHatAutor [id=" + id + ", autor=" + autor + ", dokument=" + dokument + ", bemerkung=" + bemerkung
				+ "]";
	}

}
