package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Exportdienst generated by hbm2java
 */
@Entity
@Table(name = "exportdienst", catalog = "metis")
public class Exportdienst implements java.io.Serializable {

	private int idExportDienst;
	private String dienstname;
	private String beschreibung;
	private List<Dokument> dokuments = new ArrayList<Dokument>();

	public Exportdienst() {
	}

	public Exportdienst(int idExportDienst) {
		this.idExportDienst = idExportDienst;
	}

	public Exportdienst(int idExportDienst, String dienstname, String beschreibung, List<Dokument> dokuments) {
		this.idExportDienst = idExportDienst;
		this.dienstname = dienstname;
		this.beschreibung = beschreibung;
		this.dokuments = dokuments;
	}

	@Id

	@Column(name = "idexportdienst", unique = true, nullable = false)
	public int getIdExportDienst() {
		return this.idExportDienst;
	}

	public void setIdExportDienst(int idExportDienst) {
		this.idExportDienst = idExportDienst;
	}

	@Column(name = "Dienstname", length = 10)
	public String getDienstname() {
		return this.dienstname;
	}

	public void setDienstname(String dienstname) {
		this.dienstname = dienstname;
	}

	@Column(name = "Beschreibung")
	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "dokument_ist_in_exportdienst", catalog = "metis", joinColumns = {
			@JoinColumn(name = "exportdienst_idexportDienst", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "dokument_iddokument", nullable = false, updatable = false) })
	public List<Dokument> getDokuments() {
		return this.dokuments;
	}

	public void setDokuments(List<Dokument> dokuments) {
		this.dokuments = dokuments;
	}

	@Override
	public String toString() {
		return "Exportdienst [idExportDienst=" + idExportDienst + ", dienstname=" + dienstname + ", beschreibung="
				+ beschreibung + ", dokuments=" + dokuments + "]";
	}

}
