package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Fachdatenbank generated by hbm2java
 */
@Entity
@Table(name = "fachdatenbank", catalog = "metis")
public class Fachdatenbank implements java.io.Serializable {

	private int idfachdatenbank;
	private String nameKurz;
	private String nameLang;
	private String nameFtx;
	private String ftxSystemInfoMetadataCopyright;
	private String ftxSystemInfoSupplier;
	private String ftxFormalInfoCopyright;
	private List<Konferenzreihe> konferenzreihes = new ArrayList<Konferenzreihe>();
	private List<Dokument> dokuments = new ArrayList<Dokument>();
	private List<Quelle> quelles = new ArrayList<Quelle>();
	private List<Periodika> periodikas = new ArrayList<Periodika>();

	public Fachdatenbank() {
	}

	public Fachdatenbank(String nameKurz, String nameLang, String nameFtx, String ftxSystemInfoMetadataCopyright,
			String ftxSystemInfoSupplier, String ftxFormalInfoCopyright, List<Konferenzreihe> konferenzreihes,
			List<Dokument> dokuments, List<Quelle> quelles, List<Periodika> periodikas) {
		this.nameKurz = nameKurz;
		this.nameLang = nameLang;
		this.nameFtx = nameFtx;
		this.ftxSystemInfoMetadataCopyright = ftxSystemInfoMetadataCopyright;
		this.ftxSystemInfoSupplier = ftxSystemInfoSupplier;
		this.ftxFormalInfoCopyright = ftxFormalInfoCopyright;
		this.konferenzreihes = konferenzreihes;
		this.dokuments = dokuments;
		this.quelles = quelles;
		this.periodikas = periodikas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idfachdatenbank", unique = true, nullable = false)
	public int getIdfachdatenbank() {
		return this.idfachdatenbank;
	}

	public void setIdfachdatenbank(int idfachdatenbank) {
		this.idfachdatenbank = idfachdatenbank;
	}

	@Column(name = "Namekurz", length = 25)
	public String getNameKurz() {
		return this.nameKurz;
	}

	public void setNameKurz(String nameKurz) {
		this.nameKurz = nameKurz;
	}

	@Column(name = "Namelang")
	public String getNameLang() {
		return this.nameLang;
	}

	public void setNameLang(String nameLang) {
		this.nameLang = nameLang;
	}

	@Column(name = "Nameftx", length = 4)
	public String getNameFtx() {
		return this.nameFtx;
	}

	public void setNameFtx(String nameFtx) {
		this.nameFtx = nameFtx;
	}

	@Column(name = "ftx_systeminfo_metadatacopyright")
	public String getFtxSystemInfoMetadataCopyright() {
		return this.ftxSystemInfoMetadataCopyright;
	}

	public void setFtxSystemInfoMetadataCopyright(String ftxSystemInfoMetadataCopyright) {
		this.ftxSystemInfoMetadataCopyright = ftxSystemInfoMetadataCopyright;
	}

	@Column(name = "ftx_systeminfo_supplier")
	public String getFtxSystemInfoSupplier() {
		return this.ftxSystemInfoSupplier;
	}

	public void setFtxSystemInfoSupplier(String ftxSystemInfoSupplier) {
		this.ftxSystemInfoSupplier = ftxSystemInfoSupplier;
	}

	@Column(name = "ftx_formalinfo_copyright")
	public String getFtxFormalInfoCopyright() {
		return this.ftxFormalInfoCopyright;
	}

	public void setFtxFormalInfoCopyright(String ftxFormalInfoCopyright) {
		this.ftxFormalInfoCopyright = ftxFormalInfoCopyright;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "konferenzreihe_hat_fachdatenbank", catalog = "metis", joinColumns = {
			@JoinColumn(name = "fachdatenbank_idfachdatenbank", nullable = false, updatable = false)  })
	public List<Konferenzreihe> getKonferenzreihes() {
		return this.konferenzreihes;
	}

	public void setKonferenzreihes(List<Konferenzreihe> konferenzreihes) {
		this.konferenzreihes = konferenzreihes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "dokument_hat_fachdatenbank", catalog = "metis", joinColumns = {
			@JoinColumn(name = "fachdatenbank_idfachdatenbank", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "dokument_iddokument", nullable = false, updatable = false) })
	public List<Dokument> getDokuments() {
		return this.dokuments;
	}

	public void setDokuments(List<Dokument> dokuments) {
		this.dokuments = dokuments;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "quelle_hat_fachdatenbank", catalog = "metis", joinColumns = {
			@JoinColumn(name = "fachdatenbank_idfachdatenbank", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "quelle_idquelle", nullable = false, updatable = false) })
	public List<Quelle> getQuelles() {
		return this.quelles;
	}

	public void setQuelles(List<Quelle> quelles) {
		this.quelles = quelles;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "periodika_hat_fachdatenbank", catalog = "metis", joinColumns = {
			@JoinColumn(name = "fachdatenbank_idfachdatenbank", nullable = false, updatable = false)  })
	public List<Periodika> getPeriodikas() {
		return this.periodikas;
	}

	public void setPeriodikas(List<Periodika> periodikas) {
		this.periodikas = periodikas;
	}

	@Override
	public String toString() {
		return "Fachdatenbank [idfachdatenbank=" + idfachdatenbank + ", nameKurz=" + nameKurz + ", nameLang=" + nameLang
				+ ", nameFtx=" + nameFtx + ", ftxSystemInfoMetadataCopyright=" + ftxSystemInfoMetadataCopyright
				+ ", ftxSystemInfoSupplier=" + ftxSystemInfoSupplier + ", ftxFormalInfoCopyright="
				+ ftxFormalInfoCopyright + ", konferenzreihes=" + konferenzreihes + ", dokuments=" + dokuments
				+ ", quelles=" + quelles + ", periodikas=" + periodikas + "]";
	}

}
