package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Feldtyp generated by hbm2java
 */
@Entity
@Table(name = "feldtyp", catalog = "metis")
public class Feldtyp implements java.io.Serializable {

	private int idFeldTyp;
	private int sortierung;
	private String beschreibung;
	private String ebeschreibung;
	private List<Dokfeld> dokfelds = new ArrayList<Dokfeld>();

	public Feldtyp() {
	}

	public Feldtyp(int idFeldTyp) {
		this.idFeldTyp = idFeldTyp;
	}

	public Feldtyp(int idFeldTyp, int sortierung, String beschreibung, String ebeschreibung,
			List<Dokfeld> dokfelds) {
		this.idFeldTyp = idFeldTyp;
		this.sortierung = sortierung;
		this.beschreibung = beschreibung;
		this.ebeschreibung = ebeschreibung;
		this.dokfelds = dokfelds;
	}

	@Id

	@Column(name = "idfeldtyp", unique = true, nullable = false)
	public int getIdFeldTyp() {
		return this.idFeldTyp;
	}

	public void setIdFeldTyp(int idFeldTyp) {
		this.idFeldTyp = idFeldTyp;
	}

	@Column(name = "Sortierung")
	public int getSortierung() {
		return this.sortierung;
	}

	public void setSortierung(int sortierung) {
		this.sortierung = sortierung;
	}

	@Column(name = "Beschreibung")
	public String getBeschreibung() {
		return this.beschreibung;
	}

	public void setBeschreibung(String beschreibung) {
		this.beschreibung = beschreibung;
	}

	@Column(name = "ebeschreibung")
	public String getEbeschreibung() {
		return this.ebeschreibung;
	}

	public void setEbeschreibung(String ebeschreibung) {
		this.ebeschreibung = ebeschreibung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feldtyp")
	public List<Dokfeld> getDokfelds() {
		return this.dokfelds;
	}

	public void setDokfelds(List<Dokfeld> dokfelds) {
		this.dokfelds = dokfelds;
	}

	@Override
	public String toString() {
		return "Feldtyp [idFeldTyp=" + idFeldTyp + ", sortierung=" + sortierung + ", beschreibung=" + beschreibung
				+ ", ebeschreibung=" + ebeschreibung + ", dokfelds=" + dokfelds + "]";
	}

}
