package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Formel generated by hbm2java
 */
@Entity
@Table(name = "formel", catalog = "metis")
public class Formel implements java.io.Serializable {

	private int idFormel;
	private String typ;
	private String formel;
	private String bemerkung;
	private List<Dokument> dokuments = new ArrayList<Dokument>();

	public Formel() {
	}

	public Formel(String typ, String formel, String bemerkung, List<Dokument> dokuments) {
		this.typ = typ;
		this.formel = formel;
		this.bemerkung = bemerkung;
		this.dokuments = dokuments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idformel", unique = true, nullable = false)
	public int getIdFormel() {
		return this.idFormel;
	}

	public void setIdFormel(int idFormel) {
		this.idFormel = idFormel;
	}

	@Column(name = "Typ", length = 10)
	public String getTyp() {
		return this.typ;
	}

	public void setTyp(String typ) {
		this.typ = typ;
	}

	@Column(name = "Formel")
	public String getFormel() {
		return this.formel;
	}

	public void setFormel(String formel) {
		this.formel = formel;
	}

	@Column(name = "Bemerkung")
	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "dokument_hat_formel", catalog = "metis", joinColumns = {
			@JoinColumn(name = "Formel_idformel", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Dokument_iddokument", nullable = false, updatable = false) })
	public List<Dokument> getDokuments() {
		return this.dokuments;
	}

	public void setDokuments(List<Dokument> dokuments) {
		this.dokuments = dokuments;
	}

	@Override
	public String toString() {
		return "Formel [idFormel=" + idFormel + ", typ=" + typ + ", formel=" + formel + ", bemerkung=" + bemerkung
				+ ", dokuments=" + dokuments + "]";
	}

}
