package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GuiTexte generated by hbm2java
 */
@Entity
@Table(name = "gui_texte", catalog = "metis")
public class GuiTexte implements java.io.Serializable {

	private int idText;
	private Boolean default_;
	private String text;
	private String etext;

	public GuiTexte() {
	}

	public GuiTexte(Boolean default_, String text, String etext) {
		this.default_ = default_;
		this.text = text;
		this.etext = etext;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idText", unique = true, nullable = false)
	public int getIdText() {
		return this.idText;
	}

	public void setIdText(int idText) {
		this.idText = idText;
	}

	@Column(name = "Default")
	public Boolean getDefault_() {
		return this.default_;
	}

	public void setDefault_(Boolean default_) {
		this.default_ = default_;
	}

	@Column(name = "Text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "eText")
	public String getEtext() {
		return this.etext;
	}

	public void setEtext(String etext) {
		this.etext = etext;
	}

	@Override
	public String toString() {
		return "GuiTexte [idText=" + idText + ", default_=" + default_ + ", text=" + text + ", etext=" + etext + "]";
	}

	
	
	
}
