package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Isbn generated by hbm2java
 */
@Entity
@Table(name = "isbn", catalog = "metis")
public class Isbn implements java.io.Serializable {

	private int idisbn;
	private Quelle quelle;
	private String isbn;
	private String typ;

	public Isbn() {
	}

	public Isbn(Quelle quelle, String isbn) {
		this.quelle = quelle;
		this.isbn = isbn;
	}

	public Isbn(Quelle quelle, String isbn, String typ) {
		this.quelle = quelle;
		this.isbn = isbn;
		this.typ = typ;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idisbn", unique = true, nullable = false)
	public int getIdisbn() {
		return this.idisbn;
	}

	public void setIdisbn(int idisbn) {
		this.idisbn = idisbn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quelle_idquelle", nullable = false)
	public Quelle getQuelle() {
		return this.quelle;
	}

	public void setQuelle(Quelle quelle) {
		this.quelle = quelle;
	}

	@Column(name = "ISBN", nullable = false, length = 20)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "Typ", length = 1)
	public String getTyp() {
		return this.typ;
	}

	public void setTyp(String typ) {
		this.typ = typ;
	}

	@Override
	public String toString() {
		return "Isbn [idisbn=" + idisbn + ", quelle=" + quelle + ", isbn=" + isbn + ", typ=" + typ + "]";
	}

}
