package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Klassifikation generated by hbm2java
 */
@Entity
@Table(name = "klassifikation", catalog = "metis")
public class Klassifikation implements java.io.Serializable {

	private int idklassifikation;
	private String klasse;
	private String bedeutung;
	private String ebedeutung;
	private List<DokumentHatKlassifikation> dokumentHatKlassifikations = new ArrayList<DokumentHatKlassifikation>();
	private List<Bearbeiter> bearbeiters = new ArrayList<Bearbeiter>();
	private List<Periodika> periodikas = new ArrayList<Periodika>();

	public Klassifikation() {
	}

	public Klassifikation(String klasse, String bedeutung, String ebedeutung,
			List<DokumentHatKlassifikation> dokumentHatKlassifikations, List<Bearbeiter> bearbeiters,
			List<Periodika> periodikas) {
		this.klasse = klasse;
		this.bedeutung = bedeutung;
		this.ebedeutung = ebedeutung;
		this.dokumentHatKlassifikations = dokumentHatKlassifikations;
		this.bearbeiters = bearbeiters;
		this.periodikas = periodikas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idklassifikation", unique = true, nullable = false)
	public int getIdklassifikation() {
		return this.idklassifikation;
	}

	public void setIdklassifikation(int idklassifikation) {
		this.idklassifikation = idklassifikation;
	}

	@Column(name = "Klasse", length = 4)
	public String getKlasse() {
		return this.klasse;
	}

	public void setKlasse(String klasse) {
		this.klasse = klasse;
	}

	@Column(name = "Bedeutung")
	public String getBedeutung() {
		return this.bedeutung;
	}

	public void setBedeutung(String bedeutung) {
		this.bedeutung = bedeutung;
	}

	@Column(name = "ebedeutung")
	public String getEbedeutung() {
		return this.ebedeutung;
	}

	public void setEbedeutung(String ebedeutung) {
		this.ebedeutung = ebedeutung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "klassifikation")
	public List<DokumentHatKlassifikation> getDokumentHatKlassifikations() {
		return this.dokumentHatKlassifikations;
	}

	public void setDokumentHatKlassifikations(List<DokumentHatKlassifikation> dokumentHatKlassifikations) {
		this.dokumentHatKlassifikations = dokumentHatKlassifikations;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "bearbeiter_kennt_klassifikation", catalog = "metis", joinColumns = {
			@JoinColumn(name = "klassifikation_idklassifikation", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "bearbeiter_idbearbeiter", nullable = false, updatable = false) })
	public List<Bearbeiter> getBearbeiters() {
		return this.bearbeiters;
	}

	public void setBearbeiters(List<Bearbeiter> bearbeiters) {
		this.bearbeiters = bearbeiters;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "periodika_hat_klassifikation", catalog = "metis", joinColumns = {
			@JoinColumn(name = "klassifikation_idklassifikation", nullable = false, updatable = false) })
	public List<Periodika> getPeriodikas() {
		return this.periodikas;
	}

	public void setPeriodikas(List<Periodika> periodikas) {
		this.periodikas = periodikas;
	}

	@Override
	public String toString() {
		return "Klassifikation [idklassifikation=" + idklassifikation + ", klasse=" + klasse + ", bedeutung="
				+ bedeutung + ", ebedeutung=" + ebedeutung + ", dokumentHatKlassifikations="
				+ dokumentHatKlassifikations + ", bearbeiters=" + bearbeiters + ", periodikas=" + periodikas + "]";
	}

}
