package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Konferenzverbund generated by hbm2java
 */
@Entity
@Table(name = "konferenzverbund", catalog = "metis")
public class Konferenzverbund implements java.io.Serializable {

	private int idKonferenzverbund;
	private String name;
	private List<Quelle> quelles = new ArrayList<Quelle>();
	private List<Konferenzereignis> konferenzereignises = new ArrayList<Konferenzereignis>();
	private List<Dokument> dokuments = new ArrayList<Dokument>();

	public Konferenzverbund() {
	}

	public Konferenzverbund(String name, List<Quelle> quelles, List<Konferenzereignis> konferenzereignises,
			List<Dokument> dokuments) {
		this.name = name;
		this.quelles = quelles;
		this.konferenzereignises = konferenzereignises;
		this.dokuments = dokuments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idkonferenzverbund", unique = true, nullable = false)
	public int getIdKonferenzverbund() {
		return this.idKonferenzverbund;
	}

	public void setIdKonferenzverbund(int idKonferenzverbund) {
		this.idKonferenzverbund = idKonferenzverbund;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "quelle_berichtet_ueber_konferenzverbund", catalog = "metis", joinColumns = {
			@JoinColumn(name = "Konferenzverbund_idkonferenzverbund", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Quelle_idquelle", nullable = false, updatable = false) })
	public List<Quelle> getQuelles() {
		return this.quelles;
	}

	public void setQuelles(List<Quelle> quelles) {
		this.quelles = quelles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "konferenzverbund")
	public List<Konferenzereignis> getKonferenzereignises() {
		return this.konferenzereignises;
	}

	public void setKonferenzereignises(List<Konferenzereignis> konferenzereignises) {
		this.konferenzereignises = konferenzereignises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "konferenzverbund")
	public List<Dokument> getDokuments() {
		return this.dokuments;
	}

	public void setDokuments(List<Dokument> dokuments) {
		this.dokuments = dokuments;
	}

	@Override
	public String toString() {
		return "Konferenzverbund [idKonferenzverbund=" + idKonferenzverbund + ", name=" + name + ", quelles=" + quelles
				+ ", konferenzereignises=" + konferenzereignises + ", dokuments=" + dokuments + "]";
	}

}
