package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KonferenzreiheId generated by hbm2java
 */
@Embeddable
public class KonferenzreiheId implements java.io.Serializable {

	private int idKonferenz;
	private int version;

	public KonferenzreiheId() {
	}

	public KonferenzreiheId(int idKonferenz, int version) {
		this.idKonferenz = idKonferenz;
		this.version = version;
	}

	@Column(name = "idkonferenz", nullable = false)
	public int getIdKonferenz() {
		return this.idKonferenz;
	}

	public void setIdKonferenz(int idKonferenz) {
		this.idKonferenz = idKonferenz;
	}

	@Column(name = "Version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KonferenzreiheId))
			return false;
		KonferenzreiheId castOther = (KonferenzreiheId) other;

		return (this.getIdKonferenz() == castOther.getIdKonferenz()) && (this.getVersion() == castOther.getVersion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdKonferenz();
		result = 37 * result + this.getVersion();
		return result;
	}

}
