package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lieferant generated by hbm2java
 */
@Entity
@Table(name = "lieferant", catalog = "metis")
public class Lieferant implements java.io.Serializable {

	private int idLieferant;
	private Allelaender allelaender;
	private String lieferantNameKurz;
	private String lieferantName;
	private Character typ;
	private String anrede;
	private String vorname;
	private String name;
	private String strasse;
	private String postfach;
	private String plz;
	private String ort;
	private String bundesstaat;
	private String url;
	private String email;
	private String telefon;
	private String bemerkung;
	private List<Datenlieferung> datenlieferungs = new ArrayList<Datenlieferung>();
	private List<Periodika> periodikas = new ArrayList<Periodika>();

	public Lieferant() {
	}

	public Lieferant(Allelaender allelaender, String lieferantNameKurz, String lieferantName, Character typ,
			String anrede, String vorname, String name, String strasse, String postfach, String plz, String ort,
			String bundesstaat, String url, String email, String telefon, String bemerkung,
			List<Datenlieferung> datenlieferungs, List<Periodika> periodikas) {
		this.allelaender = allelaender;
		this.lieferantNameKurz = lieferantNameKurz;
		this.lieferantName = lieferantName;
		this.typ = typ;
		this.anrede = anrede;
		this.vorname = vorname;
		this.name = name;
		this.strasse = strasse;
		this.postfach = postfach;
		this.plz = plz;
		this.ort = ort;
		this.bundesstaat = bundesstaat;
		this.url = url;
		this.email = email;
		this.telefon = telefon;
		this.bemerkung = bemerkung;
		this.datenlieferungs = datenlieferungs;
		this.periodikas = periodikas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idlieferant", unique = true, nullable = false)
	public int getIdLieferant() {
		return this.idLieferant;
	}

	public void setIdLieferant(int idLieferant) {
		this.idLieferant = idLieferant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "landcode")
	public Allelaender getAllelaender() {
		return this.allelaender;
	}

	public void setAllelaender(Allelaender allelaender) {
		this.allelaender = allelaender;
	}

	@Column(name = "Lieferantnamekurz", length = 50)
	public String getLieferantNameKurz() {
		return this.lieferantNameKurz;
	}

	public void setLieferantNameKurz(String lieferantNameKurz) {
		this.lieferantNameKurz = lieferantNameKurz;
	}

	@Column(name = "Lieferantname")
	public String getLieferantName() {
		return this.lieferantName;
	}

	public void setLieferantName(String lieferantName) {
		this.lieferantName = lieferantName;
	}

	@Column(name = "Typ", length = 1)
	public Character getTyp() {
		return this.typ;
	}

	public void setTyp(Character typ) {
		this.typ = typ;
	}

	@Column(name = "Anrede", length = 50)
	public String getAnrede() {
		return this.anrede;
	}

	public void setAnrede(String anrede) {
		this.anrede = anrede;
	}

	@Column(name = "Vorname")
	public String getVorname() {
		return this.vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Strasse")
	public String getStrasse() {
		return this.strasse;
	}

	public void setStrasse(String strasse) {
		this.strasse = strasse;
	}

	@Column(name = "Postfach")
	public String getPostfach() {
		return this.postfach;
	}

	public void setPostfach(String postfach) {
		this.postfach = postfach;
	}

	@Column(name = "PLZ", length = 45)
	public String getPlz() {
		return this.plz;
	}

	public void setPlz(String plz) {
		this.plz = plz;
	}

	@Column(name = "Ort")
	public String getOrt() {
		return this.ort;
	}

	public void setOrt(String ort) {
		this.ort = ort;
	}

	@Column(name = "Bundesstaat")
	public String getBundesstaat() {
		return this.bundesstaat;
	}

	public void setBundesstaat(String bundesstaat) {
		this.bundesstaat = bundesstaat;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Telefon")
	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	@Column(name = "Bemerkung")
	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lieferant")
	public List<Datenlieferung> getDatenlieferungs() {
		return this.datenlieferungs;
	}

	public void setDatenlieferungs(List<Datenlieferung> datenlieferungs) {
		this.datenlieferungs = datenlieferungs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lieferant")
	public List<Periodika> getPeriodikas() {
		return this.periodikas;
	}

	public void setPeriodikas(List<Periodika> periodikas) {
		this.periodikas = periodikas;
	}

	@Override
	public String toString() {
		return "Lieferant [idLieferant=" + idLieferant + ", allelaender=" + allelaender + ", lieferantNameKurz="
				+ lieferantNameKurz + ", lieferantName=" + lieferantName + ", typ=" + typ + ", anrede=" + anrede
				+ ", vorname=" + vorname + ", name=" + name + ", strasse=" + strasse + ", postfach=" + postfach
				+ ", plz=" + plz + ", ort=" + ort + ", bundesstaat=" + bundesstaat + ", url=" + url + ", email=" + email
				+ ", telefon=" + telefon + ", bemerkung=" + bemerkung + ", datenlieferungs=" + datenlieferungs
				+ ", periodikas=" + periodikas + "]";
	}

}
