package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Metisversion generated by hbm2java
 */
@Entity
@Table(name = "metisversion", catalog = "metis")
public class Metisversion implements java.io.Serializable {

	private int idmetisversion;
	private String db;
	private String dbReleasenotes;
	private String metisgui;
	private String guiReleasenotes;
	private String metisconverter;
	private String converterReleasenotes;
	private String metistransfer;
	private String transferReleasenotes;
	private String metisexport;
	private String exportReleasenotes;

	public Metisversion() {
	}

	public Metisversion(String db, String dbReleasenotes, String metisgui, String guiReleasenotes,
			String metisconverter, String converterReleasenotes, String metistransfer, String transferReleasenotes,
			String metisexport, String exportReleasenotes) {
		this.db = db;
		this.dbReleasenotes = dbReleasenotes;
		this.metisgui = metisgui;
		this.guiReleasenotes = guiReleasenotes;
		this.metisconverter = metisconverter;
		this.converterReleasenotes = converterReleasenotes;
		this.metistransfer = metistransfer;
		this.transferReleasenotes = transferReleasenotes;
		this.metisexport = metisexport;
		this.exportReleasenotes = exportReleasenotes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idmetisversion", unique = true, nullable = false)
	public int getIdmetisversion() {
		return this.idmetisversion;
	}

	public void setIdmetisversion(int idmetisversion) {
		this.idmetisversion = idmetisversion;
	}

	@Column(name = "db", length = 45)
	public String getDb() {
		return this.db;
	}

	public void setDb(String db) {
		this.db = db;
	}

	@Column(name = "db_releasenotes", length = 16777215)
	public String getDbReleasenotes() {
		return this.dbReleasenotes;
	}

	public void setDbReleasenotes(String dbReleasenotes) {
		this.dbReleasenotes = dbReleasenotes;
	}

	@Column(name = "metisgui", length = 45)
	public String getMetisgui() {
		return this.metisgui;
	}

	public void setMetisgui(String metisgui) {
		this.metisgui = metisgui;
	}

	@Column(name = "gui_releasenotes", length = 16777215)
	public String getGuiReleasenotes() {
		return this.guiReleasenotes;
	}

	public void setGuiReleasenotes(String guiReleasenotes) {
		this.guiReleasenotes = guiReleasenotes;
	}

	@Column(name = "metisconverter", length = 45)
	public String getMetisconverter() {
		return this.metisconverter;
	}

	public void setMetisconverter(String metisconverter) {
		this.metisconverter = metisconverter;
	}

	@Column(name = "converter_releasenotes", length = 16777215)
	public String getConverterReleasenotes() {
		return this.converterReleasenotes;
	}

	public void setConverterReleasenotes(String converterReleasenotes) {
		this.converterReleasenotes = converterReleasenotes;
	}

	@Column(name = "metistransfer", length = 45)
	public String getMetistransfer() {
		return this.metistransfer;
	}

	public void setMetistransfer(String metistransfer) {
		this.metistransfer = metistransfer;
	}

	@Column(name = "transfer_releasenotes", length = 16777215)
	public String getTransferReleasenotes() {
		return this.transferReleasenotes;
	}

	public void setTransferReleasenotes(String transferReleasenotes) {
		this.transferReleasenotes = transferReleasenotes;
	}

	@Column(name = "metisexport")
	public String getMetisexport() {
		return this.metisexport;
	}

	public void setMetisexport(String metisexport) {
		this.metisexport = metisexport;
	}

	@Column(name = "export_releasenotes", length = 16777215)
	public String getExportReleasenotes() {
		return this.exportReleasenotes;
	}

	public void setExportReleasenotes(String exportReleasenotes) {
		this.exportReleasenotes = exportReleasenotes;
	}

	@Override
	public String toString() {
		return "Metisversion [idmetisversion=" + idmetisversion + ", db=" + db + ", dbReleasenotes=" + dbReleasenotes
				+ ", metisgui=" + metisgui + ", guiReleasenotes=" + guiReleasenotes + ", metisconverter="
				+ metisconverter + ", converterReleasenotes=" + converterReleasenotes + ", metistransfer="
				+ metistransfer + ", transferReleasenotes=" + transferReleasenotes + ", metisexport=" + metisexport
				+ ", exportReleasenotes=" + exportReleasenotes + "]";
	}

}
