package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module", catalog = "metis")
public class Module implements java.io.Serializable {

	private int idModule;
	private String name;
	private List<Berechtigung> berechtigungs = new ArrayList<Berechtigung>();

	public Module() {
	}

	public Module(String name, List<Berechtigung> berechtigungs) {
		this.name = name;
		this.berechtigungs = berechtigungs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idmodule", unique = true, nullable = false)
	public int getIdModule() {
		return this.idModule;
	}

	public void setIdModule(int idModule) {
		this.idModule = idModule;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "berechtigung_nutzt_module", catalog = "metis", joinColumns = {
			@JoinColumn(name = "Module_idmodule", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Berechtigung_idberechtigung", nullable = false, updatable = false) })
	public List<Berechtigung> getBerechtigungs() {
		return this.berechtigungs;
	}

	public void setBerechtigungs(List<Berechtigung> berechtigungs) {
		this.berechtigungs = berechtigungs;
	}

}
