package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Seiten generated by hbm2java
 */
@Entity
@Table(name = "seiten", catalog = "metis")
public class Seiten implements java.io.Serializable {

	private int idSeiten;
	private String name;
	private String url;
	private int oben;
	private String ordnung;
	private List<Rolle> rolles = new ArrayList<Rolle>();

	public Seiten() {
	}

	public Seiten(String name, String url, int oben, String ordnung, List<Rolle> rolles) {
		this.name = name;
		this.url = url;
		this.oben = oben;
		this.ordnung = ordnung;
		this.rolles = rolles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idseiten", unique = true, nullable = false)
	public int getIdSeiten() {
		return this.idSeiten;
	}

	public void setIdSeiten(int idSeiten) {
		this.idSeiten = idSeiten;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "Oben")
	public int getOben() {
		return this.oben;
	}

	public void setOben(int oben) {
		this.oben = oben;
	}

	@Column(name = "Ordnung", length = 3)
	public String getOrdnung() {
		return this.ordnung;
	}

	public void setOrdnung(String ordnung) {
		this.ordnung = ordnung;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "rolle_sieht_seiten", catalog = "metis", joinColumns = {
			@JoinColumn(name = "Seiten_idseiten", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Rolle_idrolle", nullable = false, updatable = false) })
	public List<Rolle> getRolles() {
		return this.rolles;
	}

	public void setRolles(List<Rolle> rolles) {
		this.rolles = rolles;
	}

	@Override
	public String toString() {
		return "Seiten [idSeiten=" + idSeiten + ", name=" + name + ", url=" + url + ", oben=" + oben + ", ordnung="
				+ ordnung + ", rolles=" + rolles + "]";
	}

}
