package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "metis", uniqueConstraints = @UniqueConstraint(columnNames = "statuswert"))
public class Status implements java.io.Serializable {

	private int idstatus;
	private int statuswert;
	private String bedeutung;
	private String EBedeutung;
	private Integer hauptstatusZuordnung;
	private Boolean forGui;
	private String kommentar;
	private List<Dokument> dokuments = new ArrayList<Dokument>();

	public Status() {
	}

	public Status(int idstatus) {
		this.idstatus = idstatus;
	}

	public Status(int idstatus, int statuswert, String bedeutung, String EBedeutung, Integer hauptstatusZuordnung,
			Boolean forGui, String kommentar, List<Dokument> dokuments) {
		this.idstatus = idstatus;
		this.statuswert = statuswert;
		this.bedeutung = bedeutung;
		this.EBedeutung = EBedeutung;
		this.hauptstatusZuordnung = hauptstatusZuordnung;
		this.forGui = forGui;
		this.kommentar = kommentar;
		this.dokuments = dokuments;
	}

	@Id

	@Column(name = "idstatus", unique = true, nullable = false)
	public int getIdstatus() {
		return this.idstatus;
	}

	public void setIdstatus(int idstatus) {
		this.idstatus = idstatus;
	}

	@Column(name = "statuswert", unique = true)
	public int getStatuswert() {
		return this.statuswert;
	}

	public void setStatuswert(int statuswert) {
		this.statuswert = statuswert;
	}

	@Column(name = "bedeutung")
	public String getBedeutung() {
		return this.bedeutung;
	}

	public void setBedeutung(String bedeutung) {
		this.bedeutung = bedeutung;
	}

	@Column(name = "e_bedeutung")
	public String getEBedeutung() {
		return this.EBedeutung;
	}

	public void setEBedeutung(String EBedeutung) {
		this.EBedeutung = EBedeutung;
	}

	@Column(name = "hauptstatus_zuordnung")
	public Integer getHauptstatusZuordnung() {
		return this.hauptstatusZuordnung;
	}

	public void setHauptstatusZuordnung(Integer hauptstatusZuordnung) {
		this.hauptstatusZuordnung = hauptstatusZuordnung;
	}

	@Column(name = "for_gui")
	public Boolean getForGui() {
		return this.forGui;
	}

	public void setForGui(Boolean forGui) {
		this.forGui = forGui;
	}

	@Column(name = "kommentar")
	public String getKommentar() {
		return this.kommentar;
	}

	public void setKommentar(String kommentar) {
		this.kommentar = kommentar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public List<Dokument> getDokuments() {
		return this.dokuments;
	}

	public void setDokuments(List<Dokument> dokuments) {
		this.dokuments = dokuments;
	}

	@Override
	public String toString() {
		return "Status [idstatus=" + idstatus + ", statuswert=" + statuswert + ", bedeutung=" + bedeutung
				+ ", EBedeutung=" + EBedeutung + ", hauptstatusZuordnung=" + hauptstatusZuordnung + ", forGui=" + forGui
				+ ", kommentar=" + kommentar + ", dokuments=" + dokuments + "]";
	}

}
