package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Suchlink generated by hbm2java
 */
@Entity
@Table(name = "suchlink", catalog = "metis")
public class Suchlink implements java.io.Serializable {

	private int idSuchlink;
	private String name;
	private String suchlink;
	private String bemerkung;

	public Suchlink() {
	}

	public Suchlink(String name, String suchlink, String bemerkung) {
		this.name = name;
		this.suchlink = suchlink;
		this.bemerkung = bemerkung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idsuchlink", unique = true, nullable = false)
	public int getIdSuchlink() {
		return this.idSuchlink;
	}

	public void setIdSuchlink(int idSuchlink) {
		this.idSuchlink = idSuchlink;
	}

	@Column(name = "Name", length = 10)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Suchlink")
	public String getSuchlink() {
		return this.suchlink;
	}

	public void setSuchlink(String suchlink) {
		this.suchlink = suchlink;
	}

	@Column(name = "Bemerkung")
	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	@Override
	public String toString() {
		return "Suchlink [idSuchlink=" + idSuchlink + ", name=" + name + ", suchlink=" + suchlink + ", bemerkung="
				+ bemerkung + "]";
	}

}
