package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ThesaurusTemaRelation generated by hbm2java
 */
@Entity
@Table(name = "thesaurus_tema_relation", catalog = "metis")
public class ThesaurusTemaRelation implements java.io.Serializable {

	private int oid;
	private int termnr;
	private char rel;
	private int obertermnr;

	public ThesaurusTemaRelation() {
	}

	public ThesaurusTemaRelation(int oid, int termnr, char rel, int obertermnr) {
		this.oid = oid;
		this.termnr = termnr;
		this.rel = rel;
		this.obertermnr = obertermnr;
	}

	@Id

	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "termnr", nullable = false)
	public int getTermnr() {
		return this.termnr;
	}

	public void setTermnr(int termnr) {
		this.termnr = termnr;
	}

	@Column(name = "rel", nullable = false, length = 1)
	public char getRel() {
		return this.rel;
	}

	public void setRel(char rel) {
		this.rel = rel;
	}

	@Column(name = "obertermnr", nullable = false)
	public int getObertermnr() {
		return this.obertermnr;
	}

	public void setObertermnr(int obertermnr) {
		this.obertermnr = obertermnr;
	}

	@Override
	public String toString() {
		return "ThesaurusTemaRelation [oid=" + oid + ", termnr=" + termnr + ", rel=" + rel + ", obertermnr="
				+ obertermnr + "]";
	}

}
