package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Verlag generated by hbm2java
 */
@Entity
@Table(name = "verlag", catalog = "metis")
public class Verlag implements java.io.Serializable {

	private int idVerlag;
	private Allelaender allelaender;
	private String verlagNameKurz;
	private String verlagName;
	private String anrede;
	private String vorname;
	private String name;
	private String strasse;
	private String postfach;
	private String plz;
	private String ort;
	private String bundesstaat;
	private String url;
	private String email;
	private String telefon;
	private String bemerkung;
	private Boolean openAccess;
	private List<Protokoll> protokolls = new ArrayList<Protokoll>();
	private List<Periodika> periodikas = new ArrayList<Periodika>();
	private List<Quelle> quelles = new ArrayList<Quelle>();

	public Verlag() {
	}

	public Verlag(Allelaender allelaender, String verlagNameKurz, String verlagName, String anrede, String vorname,
			String name, String strasse, String postfach, String plz, String ort, String bundesstaat, String url,
			String email, String telefon, String bemerkung, Boolean openAccess, List<Protokoll> protokolls,
			List<Periodika> periodikas, List<Quelle> quelles) {
		this.allelaender = allelaender;
		this.verlagNameKurz = verlagNameKurz;
		this.verlagName = verlagName;
		this.anrede = anrede;
		this.vorname = vorname;
		this.name = name;
		this.strasse = strasse;
		this.postfach = postfach;
		this.plz = plz;
		this.ort = ort;
		this.bundesstaat = bundesstaat;
		this.url = url;
		this.email = email;
		this.telefon = telefon;
		this.bemerkung = bemerkung;
		this.openAccess = openAccess;
		this.protokolls = protokolls;
		this.periodikas = periodikas;
		this.quelles = quelles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idverlag", unique = true, nullable = false)
	public int getIdVerlag() {
		return this.idVerlag;
	}

	public void setIdVerlag(int idVerlag) {
		this.idVerlag = idVerlag;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "landcode")
	public Allelaender getAllelaender() {
		return this.allelaender;
	}

	public void setAllelaender(Allelaender allelaender) {
		this.allelaender = allelaender;
	}

	@Column(name = "Verlagnamekurz", length = 45)
	public String getVerlagNameKurz() {
		return this.verlagNameKurz;
	}

	public void setVerlagNameKurz(String verlagNameKurz) {
		this.verlagNameKurz = verlagNameKurz;
	}

	@Column(name = "Verlagname")
	public String getVerlagName() {
		return this.verlagName;
	}

	public void setVerlagName(String verlagName) {
		this.verlagName = verlagName;
	}

	@Column(name = "Anrede")
	public String getAnrede() {
		return this.anrede;
	}

	public void setAnrede(String anrede) {
		this.anrede = anrede;
	}

	@Column(name = "Vorname")
	public String getVorname() {
		return this.vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Strasse")
	public String getStrasse() {
		return this.strasse;
	}

	public void setStrasse(String strasse) {
		this.strasse = strasse;
	}

	@Column(name = "Postfach", length = 45)
	public String getPostfach() {
		return this.postfach;
	}

	public void setPostfach(String postfach) {
		this.postfach = postfach;
	}

	@Column(name = "PLZ", length = 45)
	public String getPlz() {
		return this.plz;
	}

	public void setPlz(String plz) {
		this.plz = plz;
	}

	@Column(name = "Ort", length = 45)
	public String getOrt() {
		return this.ort;
	}

	public void setOrt(String ort) {
		this.ort = ort;
	}

	@Column(name = "Bundesstaat")
	public String getBundesstaat() {
		return this.bundesstaat;
	}

	public void setBundesstaat(String bundesstaat) {
		this.bundesstaat = bundesstaat;
	}

	@Column(name = "URL")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "EMail", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Telefon", length = 100)
	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	@Column(name = "Bemerkung")
	public String getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}

	@Column(name = "Openaccess")
	public Boolean getOpenAccess() {
		return this.openAccess;
	}

	public void setOpenAccess(Boolean openAccess) {
		this.openAccess = openAccess;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "verlag")
	public List<Protokoll> getProtokolls() {
		return this.protokolls;
	}

	public void setProtokolls(List<Protokoll> protokolls) {
		this.protokolls = protokolls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "verlag")
	public List<Periodika> getPeriodikas() {
		return this.periodikas;
	}

	public void setPeriodikas(List<Periodika> periodikas) {
		this.periodikas = periodikas;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "quelle_hat_verlag", catalog = "metis", joinColumns = {
			@JoinColumn(name = "verlag_idverlag", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "Quelle_idquelle", nullable = false, updatable = false) })
	public List<Quelle> getQuelles() {
		return this.quelles;
	}

	public void setQuelles(List<Quelle> quelles) {
		this.quelles = quelles;
	}

	@Override
	public String toString() {
		return "Verlag [idVerlag=" + idVerlag + ", allelaender=" + allelaender + ", verlagNameKurz=" + verlagNameKurz
				+ ", verlagName=" + verlagName + ", anrede=" + anrede + ", vorname=" + vorname + ", name=" + name
				+ ", strasse=" + strasse + ", postfach=" + postfach + ", plz=" + plz + ", ort=" + ort + ", bundesstaat="
				+ bundesstaat + ", url=" + url + ", email=" + email + ", telefon=" + telefon + ", bemerkung="
				+ bemerkung + ", openAccess=" + openAccess + ", protokolls=" + protokolls + ", periodikas=" + periodikas
				+ ", quelles=" + quelles + "]";
	}

}
