package metismodel;
// default package
// Generated 05.09.2018 08:32:48 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wiedervorlage generated by hbm2java
 */
@Entity
@Table(name = "wiedervorlage", catalog = "metis")
public class Wiedervorlage implements java.io.Serializable {

	private int idwiedervorlage;
	private Bearbeiter bearbeiter;
	private Periodika periodika;
	private Date datum;
	private String hinweis;

	public Wiedervorlage() {
	}

	public Wiedervorlage(Bearbeiter bearbeiter, Periodika periodika) {
		this.bearbeiter = bearbeiter;
		this.periodika = periodika;
	}

	public Wiedervorlage(Bearbeiter bearbeiter, Periodika periodika, Date datum, String hinweis) {
		this.bearbeiter = bearbeiter;
		this.periodika = periodika;
		this.datum = datum;
		this.hinweis = hinweis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idwiedervorlage", unique = true, nullable = false)
	public int getIdwiedervorlage() {
		return this.idwiedervorlage;
	}

	public void setIdwiedervorlage(int idwiedervorlage) {
		this.idwiedervorlage = idwiedervorlage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bearbeiter_idbearbeiter", nullable = false)
	public Bearbeiter getBearbeiter() {
		return this.bearbeiter;
	}

	public void setBearbeiter(Bearbeiter bearbeiter) {
		this.bearbeiter = bearbeiter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "periodika_ZCode", referencedColumnName = "ZCode", nullable = false),
			@JoinColumn(name = "periodika_Version", referencedColumnName = "Version", nullable = false) })
	public Periodika getPeriodika() {
		return this.periodika;
	}

	public void setPeriodika(Periodika periodika) {
		this.periodika = periodika;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Datum", length = 10)
	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	@Column(name = "Hinweis")
	public String getHinweis() {
		return this.hinweis;
	}

	public void setHinweis(String hinweis) {
		this.hinweis = hinweis;
	}

}
